#!/bin/bash

empty="empty"
name=$empty
install="n"
basePath="/workspace"
success="SUCCESS"
error="ERROR"
starting="STARTING"

help_message() {
  if [[ $1 == "-h" ]]; then
    echo "Usage new_mfe.sh -p {dev port} -n {project name} [options]";
    echo "-n: Project name"
    echo "OPTIONS:"
    echo "-i: install formly into workspace (n)";
    echo "-b Root of the angular mono-repo"
    exit 0
  fi
}

validate_args() {
  if [[ $name == $empty ]] ; then
    echo "$error: Invalid arguments, please see help (-h)"
    exit 0
  fi
}

while getopts n:i:b:h flag
do
    case "${flag}" in
        n) name=${OPTARG};;
        i) install=${OPTARG};;
        b) basePath=${OPTARG};;
        h) help="-h";;
    esac
done

# display help message if -h is a commandline arg
help_message $help
validate_args

echo "#################################"
echo "$starting: Adding Formly to Project $name"
echo "#################################"

cd $basePath
projectPath="./projects/$name/src";
appPath="$projectPath/app"

if [[ $install == "y" || $install == "Y" ]]; then
    ng add @ngx-formly/schematics --ui-theme=material --project $name
    echo "$success: Formly added"
fi
mkdir -p $appPath/pages/basic-form-page/
cp -r $basePath/templates/basic-form-page/* $appPath/pages/basic-form-page/
cp $appPath/pages/basic-form-page/basic-form-page.component.spec.ts.txt $appPath/pages/basic-form-page/basic-form-page.component.spec.ts
rm $appPath/pages/basic-form-page/basic-form-page.component.spec.ts.txt
cp $appPath/pages/basic-form-page/basic-form-page.component.ts.txt $appPath/pages/basic-form-page/basic-form-page.component.ts
rm $appPath/pages/basic-form-page/basic-form-page.component.ts.txt


sed -i "s/{ ReactiveFormsModule }/{ FormsModule, ReactiveFormsModule }/g" $appPath/app.module.ts
sed -i "/^@NgModule.*/i import { BasicFormPageComponent } from './pages/basic-form-page/basic-form-page.component';" $appPath/app.module.ts

sed -i "/imports.*/a FormsModule," $appPath/app.module.ts
sed -i "/declarations.*/a BasicFormPageComponent," $appPath/app.module.ts

sed -i "/^export const APP_ROUTES: Routes.*/i import { BasicFormPageComponent } from '../pages/basic-form-page/basic-form-page.component';" $appPath/router/app.routes.ts
sed -i "/^export const APP_ROUTES: Routes.*/a { path: 'basic-form', component: BasicFormPageComponent,}," $appPath/router/app.routes.ts

echo '<div><a routerLink="/basic-form">Basic Form</a></div>' >> $appPath/pages/landing-page/landing-page.component.html
