#!/bin/bash

Color_Off='\033[0m'       # Text Reset
# Regular Colors
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Blue='\033[0;34m'         # Blue
Yellow='\033[0;33m'       # Yellow
Purple='\033[0;35m'       # Purple

remove="${Purple}DELETE${Color_Off}"
success="${Green}SUCCESS${Color_Off}"
create="${Green}CREATE${Color_Off}"
update="${Green}UPDATE${Color_Off}"
error="${Red}ERROR${Color_Off}"
starting="${Yellow}STARTING${Color_Off}"
line="${Yellow}#################################${Color_Off}"
complete="${Yellow}COMPLETED${Color_Off}"

empty="empty"
name=$empty
basePath="/workspace"

command_msg(){
  if [ $? == 0 ] ; then
    echo -e "$1 $2"
  else
    echo -e "$error $2"
    exit 1
  fi
}

# display help message if -h is a commandline arg
help_message() {
  if [[ $1 == "-h" ]]; then
    echo "Usage add-environments-to-project.sh -n {project-name}";
    echo "-n: Angular project to add environments to";
    echo "OPTIONS:"
    echo "-b Root of the angular mono-repo"
    exit 1
  fi
}

while getopts n:b:h flag
do
    case "${flag}" in
        n) name=${OPTARG};;
        b) basePath=${OPTARG};;
        h) help="-h";;
    esac
done

# display help message if -h is a commandline arg
help_message $help

echo -e $line
echo -e "$starting Adding environments to project $name"

if [[ ! -d $basePath ]]; then
  echo -e "$error Root of the angular mono-repo cannot be found ($basePath)"
  exit 1
fi

cd $basePath

projectPath="./projects/$name/src";

# if the project has been successfully created lets customise it
if [[ ! -f "$projectPath/app/app.module.ts" ]]; then
  echo -e "$error Project $name could not be found";
  exit 1;
fi

# added environment variables
cp -a ./templates/environments $projectPath
command_msg $success "environments copied to project $name"

# update angular.json with production fileReplacements for env
updatedAngularJson="$(jq ".projects.$name.architect.build.configurations.production.fileReplacements += [{\"replace\": \"projects/$name/src/environments/environment.ts\",\"with\": \"projects/$name/src/environments/environment.prod.ts\"}]" ./angular.json)"
echo -E "${updatedAngularJson}" > angular.json
command_msg $update "angular.json"

echo -e "$success Environments added to project $name"
echo -e $line

