#!/bin/bash

rm -rf ./projects
rm .editorconfig
rm angular.json
rm material.modules.ts
rm package-lock.json
rm package.json
rm README.md
rm tsconfig.json
rm -rf ./dist
rm -rf ./.vscode
rm -rf ./.angular

clear
