#!/bin/bash

Color_Off='\033[0m'       # Text Reset
# Regular Colors
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Blue='\033[0;34m'         # Blue
Yellow='\033[0;33m'       # Yellow
Purple='\033[0;35m'       # Purple

remove="${Purple}DELETE${Color_Off}"
success="${Green}SUCCESS${Color_Off}"
create="${Green}CREATE${Color_Off}"
update="${Green}UPDATE${Color_Off}"
error="${Red}ERROR${Color_Off}"
starting="${Yellow}STARTING${Color_Off}"
line="${Yellow}#################################${Color_Off}"
complete="${Yellow}COMPLETED${Color_Off}"

empty="empty"
name=$empty
project=$empty
customTypeSelection="y"
basePath="/workspace"

command_msg(){
  if [ $? == 0 ] ; then
    echo -e "$1 $2"
  else
    echo -e "$error $2"
    exit 1
  fi
}

help_message() {
  if [[ $1 == "-h" ]]; then
    echo "Usage add-formly-component.sh -n {component-name} -p {project name} [options]";
    echo "-n: Component name in (kebab-case)"
    echo "-p: Angular project name";
    echo "OPTIONS:"
    echo "-c Register as formly custom type? Y|n"
    echo "-b Root of the angular mono-repo"
    exit 1
  fi
}

validate_args() {
  if [[ $name == $empty || $project == $empty ]] ; then
    echo -e "$error Invalid arguments, please see help (-h)"
    help_message "-h"
    exit 1
  fi
}

while getopts n:p:c:b:h flag
do
    case "${flag}" in
        n) name=${OPTARG};;
        p) project=${OPTARG};;
        c) customTypeSelection=${OPTARG};;
        b) basePath=${OPTARG};;
        h) help="-h";;
    esac
done

# display help message if -h is a commandline arg
help_message $help

validate_args

echo -e $line
echo -e "$starting Creating formly component $name"

if [[ ! -d $basePath ]]; then
  echo -e "$error Root of the angular mono-repo cannot be found ($basePath)"
  exit 1
fi

cd $basePath
projectPath="./projects/$name/src";
appPath="$projectPath/app"

# kabab case name to camel case
componentName="${echo $name | sed -e "s/\b\(.\)/\u\1/g" | sed -e 's/-//g'}Component"
componentPath="./components/$name/$name.component"

ng generate component components/${name} --project=$project
command_msg $success "$name component generated"

# sed -i "/^@NgModule.*/i import { $componentName } from '$componentPath';" $appPath/app.module.ts
# sed -i "/declarations.*/a $componentName," $appPath/app.module.ts
# echo -e "$success component $name registered within app.module.ts"

if [[ $customTypeSelection == "y" || $customTypeSelection == "Y" ]]; then
    customType="{ name: $name, component: $componentName, wrappers: [] },"
    # look for //formly-types in app.module.ts and insert the new formly type above
    sed -i "/] //formly-types.*/i $customType" $appPath/app.module.ts

    command_msg $update "$appPath/app.module.ts"
fi

echo -e "$success Formly component $name created"
echo -e $line


